### ISSUE TITLE
[Overlay]Overlay组件的计算相对视口的位置问题

### ISSUE THREAD

**Issue by smancang** [alibaba-fusion/next#413] opened 2019-03-05 09:30 UTC
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.13.4

### Component
Overlay

### Environment
mac chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/9b419e41](https://riddle.alibaba-inc.com/riddles/9b419e41)

### Steps to reproduce
打开重现链接，可以看到底下的翻页组件Pagination，点“每页显示”右侧的下拉会发现它向下展开了选项。按照显示在视口中的原则理应向上展开的。

然后我看源码最终定位到了Overlay组件，其内部utils/position.js里计算元素相对视口的方法_getElementReact有问题，其只考虑了在body上滚动，如果元素在一个父级为div中滚动则算出的相对视口左上角的位置是错的。 image

期望结果：
修正错误的计算方法， 直接将这整个方法用原生的getBoundingClientRect代替即可解决问题

**Comment by jdkahn** [comment] 2019-03-06 05:27
@smancang Please close this issue if it was resolved by updating the version

**Comment by youluna** [comment] 2019-03-06 13:19
@smancang solved in ^1.13.3

**Comment by smancang** [comment] 2019-04-09 05:48
The issue comes back again at the latest version 1.13.12

**Comment by jdkahn** [comment] 2019-04-12 02:23
@smancang Please confirm that the issue is resolved. You can either add `position: relative` to the element with `overflow: auto;` or add `popupProps={{align: 'bl tl'}}` to the Pagination component.

**Comment by jdkahn** [comment] 2019-04-23 03:47
Resolved in next@1.14.0

**Closed by jdkahn** 2019-04-23 03:47 UTC
