### ISSUE TITLE
[Tab]Extra content covers excess-mode buttons

### ISSUE THREAD

**Issue by guanpu** [alibaba-fusion/next#269] opened 2019-01-30 03:21 UTC
- [x] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.12.3

### Component
Tab

### Environment
Any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/olj80p338y)

### Steps to reproduce
1. Enable excess mode and add enough tabs
2. Add extra content like a button or so
3. Can't use excess mode slide-to-left or slide-to-right buttons

**Comment by youluna** [comment] 2019-02-22 04:40
Any process？ @guanpu

**Comment by guanpu** [comment] 2019-02-22 04:48
I only managed to figure out why, didn’t come up with a solution which don’t introduce breaking changes yet.

**Comment by guanpu** [comment] 2019-02-23 08:06
![image](https://user-images.githubusercontent.com/5867109/53283664-95cd9600-3784-11e9-9146-be5b01dd30af.png)

This is current DOM structure, if we want to solve this, an elegant way I think is to make "excess buttons" a part of extra-content.  like this:
`
<div class="extra-content">
  <div class="custom-extra-content"></div>
  <div class="slider-extra-content">
     <button>prev</button>
     <button>next</button>
  </div>
</div>
`

**Comment by youluna** [comment] 2019-03-04 08:39
Is this issue proposed by a user? If not, I think we can just close this issue and add some tips in docs write as 'Make sure you have limited tabs and won't make the excess-mode button apprears which will definitely conflict with extra content'

**Comment by guanpu** [comment] 2019-03-04 09:04
That's my initial thoughts, and I'll add the hint documentation, but it won't hurt to keep this issue open, as it would be better is we solve this gracefully in future.

**Comment by youluna** [comment] 2019-03-04 09:33
They are inconsistent by design. Consider this in 2.x

**Closed by youluna** 2019-03-04 09:33 UTC
Labels: wontfix
