### ISSUE TITLE
[Overlay] different position result between 1.10.x & 1.11.x

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#232] opened 2019-01-24 05:56 UTC
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Version
1.11.11

### Component
Overlay

### Environment
Mac

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ov6r9j1y15)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/10049465/51656549-84099f00-1fdc-11e9-81f0-d3ca90cbfc9d.png)
1. The picture above shows the menu in position {left: 421px; top: 96px;} 
2.If I move my mouse to right a little bit, then right click, the menu will apprear in position {left: 0, right: 0}
      
The problem may be caused by the fucntion setPosition in `./src/overlay/utils/position.js`. There is a change between 1.10.x and 1.11.x to support rtl   https://github.com/alibaba-fusion/next/commits/master/src/overlay/utils/position.js

**Comment by youluna** [comment] 2019-01-24 06:33
![image](https://user-images.githubusercontent.com/10049465/51659037-6c361900-1fe4-11e9-9930-be1c49c7192b.png)
![image](https://user-images.githubusercontent.com/10049465/51659138-aef7f100-1fe4-11e9-9cb4-dde0eb9de56a.png)
The first is `top: 719.188px`, and second is `top: 731.188px;`
https://fusion.design/component/balloon
This  may relative to Overlay, too.  It behave diffrent between 1.10.x and 1.11.x when there is no enough space for overlay.

**Comment by jdkahn** [comment] 2019-02-03 09:58
@youluna I'm unable to reproduce the error you mentioned using the link you sent. I also had to modify the import to just `import { Button, Menu } from "@alifd/next";` to get it to work. I tried 1.10.x, 1.11.x, and latest and could not reproduce

**Comment by youluna** [comment] 2019-02-20 13:34
![image](https://user-images.githubusercontent.com/10049465/53095211-2aeb4780-3557-11e9-97a9-513b49ab96f9.png)
Demo updated. It happends when there is no enough space on the right side for menu

**Comment by jdkahn** [comment] 2019-02-22 09:43
The issue with `Balloon` is caused by adjustments to place the tooltip in the viewport and a bug to ignore offsets when it cannot be in the viewport. This will be fixed in https://github.com/alibaba-fusion/next/pull/372.

The issue with the `Context Menu` has also been fixed with functionality reverting back to how it was in 1.10.x where the menu will always appear at the location of the right click, even if that has the menu appear off-screen. The developer using the component can add logic to adjust the offset as they want.

**Comment by jdkahn** [comment] 2019-02-28 08:56
Resolved in https://github.com/alibaba-fusion/next/pull/372

**Closed by jdkahn** 2019-02-28 08:56 UTC
