### ISSUE TITLE
[Dialog]Support Dialog draggable / 窗口支持可拖动

### ISSUE THREAD

**Issue by tao1991123** [alibaba-fusion/next#272] opened 2019-01-30 07:58 UTC
- [ ] I have searched the [issues](https://github.com/alibaba-fusion/next/issues) of this repository and believe that this is not a duplicate.

### Component
Dialog

### Feature Description
# EN

Support drag the diaolog both full dialog drag and title drag， similar to the MS Window native dialog
# CN

支持全框点击拖动（alert场景）和只标题区域点击可拖动（有children场景）

**Comment by jdkahn** [comment] 2019-04-18 10:51
@tao1991123 Do you mean draggable to relocate the dialog or to be able to resize the dialog, or both?

**Comment by jdkahn** [comment] 2019-04-23 03:45
Duplicate of https://github.com/alibaba-fusion/next/issues/231

**Closed by jdkahn** 2019-04-23 03:45 UTC
Labels: enhancement, good first issue

**Comment by bindoon** [comment] 2021-09-17 11:27
will support in @alifd/next@1.25
